name: Run Tests and Publish Coverage Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to 'windows-latest' or 'macos-latest' if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Replace with the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest and collect coverage
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Runs the tests
          coverage run -m pytest  # Runs tests and collects coverage data
          coverage html  # Generates the HTML coverage report
          
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: htmlcov/index.html  # Path to the generated HTML report

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: tests/results.xml  # Path to any test result XML (optional, if you want to upload a test result file)
